-- 1. Criar a Tabela de Roles (Dinâmico)
CREATE TABLE IF NOT EXISTS public.app_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  is_system boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. Migrar os Enums atuais para a nova tabela
INSERT INTO public.app_roles (name, is_system)
VALUES 
  ('admin', true),
  ('pastor', false),
  ('lider', false),
  ('secretario', false),
  ('tesoureiro', false),
  ('membro', false),
  ('basico', true)
ON CONFLICT (name) DO NOTHING;

-- 3. Tabela de Permissões
CREATE TABLE IF NOT EXISTS public.app_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE, 
  name text NOT NULL,       
  module text NOT NULL,     
  description text
);

-- 4. Tabela de Ligação Role <-> Permissão
CREATE TABLE IF NOT EXISTS public.role_permissions (
  role_id bigint REFERENCES public.app_roles(id) ON DELETE CASCADE,
  permission_id bigint REFERENCES public.app_permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

-- 5. Nova tabela de ligação Usuário -> Role
CREATE TABLE IF NOT EXISTS public.user_app_roles (
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  role_id bigint REFERENCES public.app_roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

-- 6. Sincronizar dados existentes (role é o nome da coluna, app_role é o tipo enum)
INSERT INTO public.user_app_roles (user_id, role_id)
SELECT 
  ur.user_id, 
  ar.id 
FROM public.user_roles ur
JOIN public.app_roles ar ON ar.name = ur.role::text
ON CONFLICT DO NOTHING;

-- 7. Habilitar RLS nas novas tabelas
ALTER TABLE public.app_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_app_roles ENABLE ROW LEVEL SECURITY;

-- 8. Políticas RLS para app_roles
CREATE POLICY "Todos podem ver roles" ON public.app_roles FOR SELECT USING (true);
CREATE POLICY "Admins podem gerenciar roles" ON public.app_roles FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- 9. Políticas RLS para app_permissions
CREATE POLICY "Todos podem ver permissões" ON public.app_permissions FOR SELECT USING (true);
CREATE POLICY "Admins podem gerenciar permissões" ON public.app_permissions FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- 10. Políticas RLS para role_permissions
CREATE POLICY "Todos podem ver role_permissions" ON public.role_permissions FOR SELECT USING (true);
CREATE POLICY "Admins podem gerenciar role_permissions" ON public.role_permissions FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- 11. Políticas RLS para user_app_roles
CREATE POLICY "Usuários podem ver seus próprios roles" ON public.user_app_roles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins podem ver todos os roles" ON public.user_app_roles FOR SELECT USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Admins podem gerenciar user_app_roles" ON public.user_app_roles FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));